---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure the test container is absent
      containers.podman.podman_container:
        name: restic-backup-instance
        state: absent
