---
# defaults file for cloudflare_ssl
cloudflare_ssl_debian_packages:
  - python3-certbot
  - python3-certbot-dns-cloudflare

cloudflare_ssl_fedora_packages:
  - python3-certbot
  - python3-certbot-dns-cloudflare
