---
# tasks/docker_setup.yml - Install and configure Docker

- name: Set Docker repo distro
  ansible.builtin.set_fact:
    _docker_repo_distro: "{{ 'ubuntu' if ansible_facts['distribution'] == 'Ubuntu' else 'debian' }}"
  when: install_docker

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ _docker_repo_distro }}/gpg"
    state: present
  become: true
  when: install_docker

- name: Set Docker repo architecture
  ansible.builtin.set_fact:
    _docker_repo_arch: >-
      {{ ansible_facts['architecture'] | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}
  when: install_docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ _docker_repo_arch }}]
      https://download.docker.com/linux/{{ _docker_repo_distro }}
      {{ ansible_facts['distribution_release'] }} stable
    state: present
  become: true
  when: install_docker

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  when: install_docker

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ toolkit_user }}"
    groups: docker
    append: true
  become: true
  when: install_docker

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
  when: install_docker
